version: '3'
services:
  golang-cicd:
    container_name: golang-api
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "8000:8000"
    command: go run /app/main.go -b 0.0.0.0